import { Helmet } from 'react-helmet-async'
import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

export default function PrivacyPolicy() {
  return (
    <>
      <Helmet>
        <title>Privacy Policy | HorseCost</title>
        <meta name="description" content="HorseCost privacy policy. Learn how we protect your data and personal information." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://horsecost.co.uk/privacy-policy" />
      </Helmet>

      <div className="bg-white">
        <div className="bg-amber-50 border-b border-amber-200 py-8 px-4 sm:px-6">
          <div className="max-w-4xl mx-auto">
            <Link to="/" className="flex items-center gap-2 text-amber-700 hover:text-amber-800 font-semibold mb-4">
              <ArrowLeft className="w-5 h-5" />
              Back to Home
            </Link>
            <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
            <p className="text-gray-600 mt-2">Last updated: November 2025</p>
          </div>
        </div>

        <div className="py-12 px-4 sm:px-6">
          <div className="max-w-4xl mx-auto space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
              <p className="text-gray-700 mb-4">
                HorseCost ("we," "us," "our," or "Company") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website horsecost.co.uk (the "Site") and use our services.
              </p>
              <p className="text-gray-700">
                Please read this Privacy Policy carefully. If you do not agree with our policies and practices, please do not use our Site.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Information We Collect</h2>
              <h3 className="text-xl font-semibold text-gray-800 mb-3">Information You Provide Directly:</h3>
              <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
                <li>Contact information (name, email address) when you sign up for updates</li>
                <li>Feedback and feature requests submitted through our contact forms</li>
                <li>Any other information you choose to provide</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Information Collected Automatically:</h3>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Device information (browser type, operating system, device identifiers)</li>
                <li>Usage data (pages visited, time spent, calculator features used)</li>
                <li>IP address and approximate location</li>
                <li>Cookies and similar tracking technologies</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. How We Use Your Information</h2>
              <p className="text-gray-700 mb-4">We use the information we collect for the following purposes:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>To provide, maintain, and improve our Services</li>
                <li>To send you updates about new calculators and features</li>
                <li>To respond to your inquiries and support requests</li>
                <li>To analyze usage patterns and improve user experience</li>
                <li>To comply with legal obligations</li>
                <li>To prevent fraud and enhance security</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Calculation Data</h2>
              <p className="text-gray-700 mb-4">
                <strong>Important:</strong> All calculator inputs and results are processed entirely on your device. We do NOT collect, store, or transmit:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Your horse business data or calculations</li>
                <li>Numbers entered into calculators</li>
                <li>Personal or financial information used in calculations</li>
                <li>Results or estimates generated by calculators</li>
              </ul>
              <p className="text-gray-700 mt-4">
                This data remains private on your device and is never sent to our servers.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Third-Party Services</h2>
              <p className="text-gray-700 mb-4">We use the following third-party services:</p>
              
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Google Analytics 4</h3>
              <p className="text-gray-700 mb-4">
                We use Google Analytics to understand how visitors use our Site. Google Analytics collects information such as how often users visit, what pages they visit, and what other sites they used prior to coming to our Site. We do not combine the information collected through Google Analytics with personally identifiable information.
              </p>

              <h3 className="text-lg font-semibold text-gray-800 mb-2">SmartSuite</h3>
              <p className="text-gray-700 mb-4">
                Information you submit through contact forms is sent to SmartSuite for processing and storage. Please review SmartSuite's privacy policy at smartsuite.com/privacy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Cookies and Tracking</h2>
              <p className="text-gray-700 mb-4">
                Our Site uses cookies to enhance your experience. Cookies are small files placed on your device that help us recognize you and customize your experience. You can control cookie settings through your browser preferences.
              </p>
              <p className="text-gray-700">
                We may also use tracking pixels and similar technologies to measure advertising effectiveness and understand user behavior.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Data Retention</h2>
              <p className="text-gray-700">
                We retain personal information you provide only as long as necessary to fulfill the purposes for which it was collected or as required by law. If you request deletion of your information, we will remove it within 30 days, except where retention is required by law or legitimate business purposes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Data Security</h2>
              <p className="text-gray-700">
                We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet or electronic storage is completely secure.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Your Rights</h2>
              <p className="text-gray-700 mb-4">Under GDPR and UK data protection laws, you have the right to:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Access your personal data</li>
                <li>Correct inaccurate data</li>
                <li>Request deletion of your data</li>
                <li>Object to data processing</li>
                <li>Request restriction of processing</li>
                <li>Receive your data in a portable format</li>
              </ul>
              <p className="text-gray-700 mt-4">
                To exercise these rights, please contact us at hello@horsecost.co.uk.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Contact Us</h2>
              <p className="text-gray-700">
                If you have questions about this Privacy Policy or our privacy practices, please contact us at:
              </p>
              <div className="mt-4 p-4 bg-amber-50 rounded-lg border border-amber-200">
                <p className="font-semibold text-gray-900">HorseCost</p>
                <p className="text-gray-700">Email: hello@horsecost.co.uk</p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  )
}
